### ISSUE TITLE
Windows error: no module named fcntl

### ISSUE THREAD

**Issue by plr0201** [xapple/fasta#1]
Fasta module core.py used "import fcntl" (for non-blocking read?), and can't be used in py 3.8.8 under win10 x64. It seems fcntl is for linux only? I searched pypl and can't find fcntl module, pip also doesn't work. fasta should work in windows according to the description, then what's my problem? Any solution for me to fix this? 
Thanks in advance!
Following is the error message
Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\111a\AppData\Local\Programs\Python\Python38\lib\site-packages\fasta\__init__.py", line 23, in <module>
    from fasta.core      import FASTA
  File "C:\Users\111a\AppData\Local\Programs\Python\Python38\lib\site-packages\fasta\core.py", line 26, in <module>
    import sh
  File "C:\Users\111a\AppData\Local\Programs\Python\Python38\lib\site-packages\sh.py", line 41, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

C:\Users\111a>pip install fcntl
ERROR: Could not find a version that satisfies the requirement fcntl (from versions: none)
ERROR: No matching distribution found for fcntl

**Comment by xapple** [comment]
Thanks for the bug report. I hadn't tested the library on Windows in a long time. It turns out that the `sh` dependency we use to launch external commands does not support Windows at all.

The latest version 2.2.13 should fix this. When on Windows, we import `pbs3` now instead of `sh`, which has similar functionality. Don't hesitate to comment if it still doesn't work.
